/* ==========================================================================
   nectar-design — Sub-brand runtime registry
   GENERATED by scripts/build-sub-brands.mjs from tokens/sub-brands/*.json.
   Do not edit manually (ADR 0026). Consumed by SubBrandProvider.
   ========================================================================== */

export type AtmospherePreset = 'none' | 'orbs' | 'heat' | 'birds' | 'ink-route';
export type HeroComposition = 'default' | 'ink-led' | 'photo-led' | 'typography-led';

export interface SubBrandAssets {
  logo?: string;
  logoMark?: string;
  favicon?: string;
  ogImage?: string;
}

export interface SubBrandRecord {
  name: string;
  displayName: string;
  atmosphere: AtmospherePreset;
  hero: HeroComposition;
  tagline: string | null;
  assets: SubBrandAssets;
  routes: string[];
}

/** Master-brand fallbacks used when no SubBrandProvider is mounted. */
export const MASTER_DEFAULTS = {
  atmosphere: "orbs" as AtmospherePreset,
  hero: "default" as HeroComposition,
  tagline: null as string | null,
} as const;

/** All registered sub-brands, keyed by slug. Single source of truth: tokens/sub-brands/*.json. */
export const SUB_BRANDS: Record<string, SubBrandRecord> = {
  "ambiguity": {
    "name": "ambiguity",
    "displayName": "Ambiguity",
    "atmosphere": "ink-route",
    "hero": "typography-led",
    "tagline": "A case study on systemic uncertainty",
    "assets": {},
    "routes": [
      "/projects/ambiguity"
    ]
  },
  "systems-thinking": {
    "name": "systems-thinking",
    "displayName": "Systems Thinking Experiments",
    "atmosphere": "heat",
    "hero": "ink-led",
    "tagline": "Notes from thinking in systems",
    "assets": {},
    "routes": [
      "/projects/systems-thinking-experiments"
    ]
  }
};

/** Convenience list of all sub-brand slugs. */
export const SUB_BRAND_NAMES: readonly string[] = ["ambiguity","systems-thinking"];
